### PR TITLE
Adds installation instructions and serve script

### PR DESCRIPTION
**Pull request by vkammerer**
Hello @toxicFork , thanks for the great lib!

Just because it took me a bit of time to have the examples running locally, I added installing instructions to the README, and a small script to make it easier to run webpack-dev-server.

### CODE REVIEW

**Comment by toxicFork** [comment]
Thanks @vkammerer :) I currently use gulp for different ways of testing or building, instead of serve I'm thinking of `gulp webpack-dev-server`, but if you and others don't really like gulp I can add the other scripts instead

**Comment by vkammerer** [comment]
ok sure, that sounds good too, the PR could be changed to make it run through gulp then :) The only thing that would be nice is to have no dependency on a globally installed package. So maybe the 'serve' script should run
`
node ./node_modules/gulp/index webpack-dev-server
`
?

**Comment by toxicFork** [comment]
Good point, I will check if I can remove more "-g" dependencies as well :)

**Comment by vkammerer** [comment]
I just updated the PR, so that the npm script runs the task through gulp. No -g dependency is needed that way. Does that look good to you?

**Comment by toxicFork** [comment]
Ah cool :) I'll merge it soon, thanks!

**Pull request merged**
